version: "3.8"

services:
  postgres_db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:4.30
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - test-network

  flask-app:
    image: ./flask_app
    restart: on-failure
    env_file:
      - .env.list
    ports:
      - "8000:8000"


volumes:
  db-data:
  pgadmin-data:

networks:
  default:
    external: true
    name: my-default-network

  test-network:
    driver: bridge